---
- name: Install sdk
  shell: >
    curl -s "https://get.sdkman.io" | bash
  tags:
    - java 
    - gradle

- name: Install java
  shell: >
    /bin/bash -c "source ~/.sdkman/bin/sdkman-init.sh"
    sdk install java 11.0.11.j9-adpt
    sdk install gradle
  tags:
    - java 
    - gradle