---
- name: NVM | Downloan nvm
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh dest=/tmp/nvm_install.sh
  tags:
    - nvm

- name: Add execute permisstion to file
  file: path=/tmp/nvm_install.sh mode=0755
  tags:
    - nvm

- name: NVM | Install nvm
  shell: /tmp/nvm_install.sh
  tags:
    - nvm

- name: Source nvm in ~/.zshrc
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 0.10 && nvm alias default 0.10"
    creates=/home/{{ ansible_user_id }}/.nvm/alias
  tags:
    - nvm

- name: Install nodejs
  shell: nvm install node
  tags:
    - nvm 
    - node
