---
- name: NVM | Downloan nvm
  get_url: url=https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh dest=/tmp/nvm_install.sh
  tags:
    - nvm

- name: Add execute permisstion to file
  file: path=/tmp/nvm_install.sh mode=0755
  tags:
    - nvm

- name: NVM | Install nvm
  shell: /tmp/nvm_install.sh
  tags:
    - nvm

- name: Install Node
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts --default"
    creates=/home/{{ ansible_user_id }}/.nvm/alias
  tags:
    - nvm