---
- name: Ensure presence of bash_profile
  file: state=touch path={{home_dir}}/.bash_profile

- name: Load bashrc in bash_profile
  lineinfile: dest={{ home_dir }}/.bash_profile regexp="\. \$HOME\/\.bashrc" line="[[ -r $HOME/.bashrc ]] && . $HOME/.bashrc"

- name: Ensure presence of bashrc
  file: state=touch path={{ home_dir }}/.bashrc

- name: Add ll alias
  lineinfile: dest={{ home_dir }}/.bashrc regexp="^alias ll" line="alias ll='ls -lah'"

- name: Remove outdated homebrew taps
  homebrew_tap: tap={{ item }} state=absent
  with_items:
    - phinze/cask

- name: Install homebrew taps (needed to install 'apps' with homebrew)
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions
    - homebrew/binary
    - homebrew/dupes
    - homebrew/versions
    - thoughtbot/formulae

- name: Install 'homebrew' packages
  homebrew: pkg={{ item }} state=present
  with_items: brew_packages

- name: Install 'apps' with brew-cask
  homebrew_cask: name={{ item }} state=installed
  ignore_errors: yes
  with_items: mac_apps

- name: Uninstall 'apps' with brew-cask
  homebrew_cask: name={{ item }} state=absent
  ignore_errors: yes
  with_items:
    - cocoapods

- name: Cleanup 'homebrew'
  command: brew prune && brew cleanup && brew tap --repair

- name: Install 'npm' packages
  npm: name={{ item }} global=yes state=present
  with_items: npm_packages

- name: Install 'janus' for 'vim'
  shell: curl -Lo- https://bit.ly/janus-bootstrap | bash
         creates={{ lookup('env','HOME') }}/.vim/janus

- name: Install 'vim' plugins
  git: repo=git://github.com/{{ item.name }}/{{ item.repo }}.git
       dest={{ lookup('env','HOME') }}/.janus/{{ item.repo }}
       update=no
       accept_hostkey=yes
  with_items:
    - { name: 'vim-scripts', repo: 'Auto-Pairs' }
    - { name: 'vim-scripts', repo: 'Align' }
    - { name: 'Lokaltog', repo: 'vim-powerline' }
    - { name: 'rizzatti', repo: 'funcoo.vim' }
    - { name: 'rizzatti', repo: 'dash.vim' }

- name: Enable zsh in /etc/shells
  sudo: yes
  lineinfile: dest=/etc/shells line="/usr/local/bin/zsh"

- name: Install 'oh-my-zsh'
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
         creates={{ lookup('env','HOME') }}/.oh-my-zsh

#
# Ruby
#
- name: Install ruby versions
  command: rbenv install {{ item }} --skip-existing creates={{ lookup('env','HOME') }}/.rbenv/versions/{{ item }}
  with_items:
    - 2.2.2

- name: Set global ruby versions
  command: rbenv global 2.2.2

- name: Install gems
  gem: name={{ item }} state=present
  with_items: gem_packages

- name: Setup Pod
  command: pod setup

- name: Install python package manager 'pip'
  sudo: yes
  shell: /usr/bin/easy_install pip
         creates=/usr/local/bin/pip

- name: Install 'pip' packages
  pip: name={{ item }} state=present
  with_items: pip_packages   

- name: Create link file
  file: src={{ item.path }} dest={{ item.dest }} state=link
  with_items: link_files

