---
- name: Check Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: brew_installed

- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: brew_installed.stat.exists == false

- name: Remove outdated homebrew taps
  homebrew_tap: tap={{ item }} state=absent
  with_items:
    - phinze/cask

- name: Install homebrew taps (needed to install 'apps' with homebrew)
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions
    - homebrew/binary
    - homebrew/dupes
    - homebrew/versions
    - thoughtbot/formulae

- name: Install 'homebrew' packages
  homebrew: pkg={{ item }} state=present
  with_items:
    - htop
    - tree
    - wget
    - zsh

- name: Install 'apps' with brew-cask
  homebrew_cask: name={{ item }} state=installed
  ignore_errors: yes
  with_items:
    - atom
    - evernote
    - flux
    - gas-mask
    - iterm2
    - mysqlworkbench
    - smcfancontrol
    - sourcetree
    - tunnelblick

- name: Uninstall 'apps' with brew-cask
  homebrew_cask: name={{ item }} state=absent
  ignore_errors: yes
  with_items:
    - cocoapods

- name: Cleanup 'homebrew'
  command: brew prune && brew cleanup && brew tap --repair

- name: Install 'janus' for 'vim'
  shell: curl -Lo- https://bit.ly/janus-bootstrap | bash
         creates={{ lookup('env','HOME') }}/.vim/janus

- name: Install 'vim' plugins
  git: repo=git://github.com/{{ item.name }}/{{ item.repo }}.git
       dest={{ lookup('env','HOME') }}/.janus/{{ item.repo }}
       update=no
       accept_hostkey=yes
  with_items:
    - { name: 'vim-scripts', repo: 'Auto-Pairs' }
    - { name: 'vim-scripts', repo: 'Align' }
    - { name: 'Lokaltog', repo: 'vim-powerline' }
    - { name: 'rizzatti', repo: 'funcoo.vim' }
    - { name: 'rizzatti', repo: 'dash.vim' }

- include: zsh.yml
# - include: vim.yml
- include: python.yml

# - name: Ensure presence of launchd.conf
#   file: state=touch path=/etc/launchd.conf
#   sudo: yes

# - name: Add environment variable
#   lineinfile: dest=/etc/launchd.conf regexp="^{{ item }}" line="{{ item }}"
#   with_items: environment_variables
#   sudo: yes
