---
- name: Install docker
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - docker

- name: Install docker packages
  homebrew: pkg={{ item }} state=present
  with_items:
    - docker-compose
    - docker-machine
  tags:
    - docker
